spring:
  application:
    name: demo-consumer
  cloud:
    nacos:
      discovery:
        # Nacos 作为注册中心的配置项，对应 NacosDiscoveryProperties 配置类
        server-addr: http://dev-internal.nacos2.codemao.cn:8848

server:
  port: 28080


feign:
  # Feign Apache HttpClient 配置项，对应 FeignHttpClientProperties 配置属性类
  httpclient:
    enabled: false # 是否开启。默认为 true
  okhttp:
    enabled: true
