server:
  port: 9090

security:
  oauth2:
    # OAuth2 Client 配置，对应 OAuth2ClientProperties 类
    client:
      clien-id: clientapp
      client-secret: 112233
    # OAuth2 Resource 配置，对应 ResourceServerProperties 类
    resource:
      token-info-uri: http://localhost:8081/oauth/check_token # 获得Token信息的URI
    # 访问令牌获取URL,自定义的.
    access-token-uri: http://localhost:8081/oauth/token

