server:
  port: 9990

spring:
  application:
    name: reactive-demo
  r2dbc:
    url: r2dbc:mysql://localhost:3306/r2dbcs_account
    username: root
    password: 12345678
#  main:
#    web-application-type: reactive