spring:
  application:
    name: spring-boot-eureka-server

server:
  port: 8761
eureka:
  instance:
    prefer-ip-address: false
  server:
    service-url:
      #      defaultZone: # 除非有等价集群，否则直接 http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
#      defaultZone: http://root:123456@localhost:8761/eureka
      defaultZone: http://localhost:8761/eureka
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    com.netflix: debug