spring:
  application:
    name: spring-boot-eureka-client

server:
  port: 10001
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      #      defaultZone: # 除非有等价集群，否则直接 http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://root:123456@localhost:8761/eureka

logging:
  level:
    com.netflix: debug