spring:
  application:
    name: lab-01-springsecurity-demo
  # Spring Security 配置项，对应 SecurityProperties 配置类
  security:
    user:
      name: user # 账号
      password: user # 密码
      roles: ADMIN  # 拥有角色
server:
  port: 10001
