server:
  port: 8888

spring:
  application:
    name: gateway-application
  cloud:
    # Spring Cloud Gateway 配置项，对应 GatewayProperties 类
    gateway:
      # 路由配置项，对应 RouteDefinition 数组
      routes:
        - id: user-service-prod # 路由编号
          uri: http://www.iocoder.cn  # 路由到的目标地址
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/**
            - Weight=user-service, 90
        - id: user-service-canary # 路由编号
          uri: https://www.oschina.net  # 路由到的目标地址
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/**
            - Weight=user-service, 10