management:
  endpoints:
    web:
      base-path: /actuator # Actuator 提供的 API 接口的根目录。默认为 /actuator
      exposure:
        include: '*'  # 需要开放的端点。默认值只打开 health 和 info 两个端点。通过设置 * ，可以开放所有端点。
        exclude: # 在 include 的基础上，需要排除的端点。通过设置 * ，可以排除所有端点。


spring:
  application:
    name: lab-34-actuator-security
  security:
    # Spring Security 配置项，对应 SecurityProperties 配置类
    user:
      name: user # 账号
      password: user # 密码
      role: ADMIN # 拥有角色
server:
  port: 10347