---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shanjian.
--- DateTime: 2024/8/12 19:38
---
local function luaSplit(str, sep)
    local result = {}
    if str == nil or sep == nil or type(str) ~= "string" or type(sep) ~= "string" then
        return result
    end
    if string.len(sep) == 0 then
        return result
    end
    local pattern = string.format("([^%s]+)", sep)
    string.gsub(
            str,
            pattern,
            function(c)
                result[#result + 1] = c
            end
    )
    return result
end

-- 时段承载 rediskey
local timeAllowance = KEYS[1]
-- 班期时段承载 rediskey
local periodAllowance = KEYS[2]
-- 用户交接抢班状态
local grabTimekey = KEYS[3]
-- 预交接记录id
local handoverId = KEYS[4]
-- 老师班级容量redisKey前缀
local teacherClassCapacity = KEYS[5]
-- 老师时段承载rediskey 前缀
local teacherTimeCapacity = KEYS[6]
-- 所选星期和时段
local weekDayTime = ARGV[1]
-- 班期id
local classPeriodId = ARGV[2]

-- 判断抢时段状态key是否存在，不存在可抢时段
if redis.call('exists', grabTimekey) == 1 then
    -- 判断handoverId属性值是否存在，不存在可抢时段
    local value = redis.call('HGET', grabTimekey, handoverId)
    if value then
        -- 抢时段成功，不可再抢
        if value == '1' then
            return 1
            -- 分班成功，不可再抢
        elseif value == '2' then
            return 2
        end
    end
end

-- 抢时段资源redis key 是否存在
if redis.call('exists', timeAllowance) == 0 then
    return 0
end
-- 获取 freeze, load 和 capacity 值
local freeze = tonumber(redis.call('hget', timeAllowance, 'freeze') or 0)
local load = tonumber(redis.call('hget', timeAllowance, 'load') or 0)
local capacity = tonumber(redis.call('hget', timeAllowance, 'capacity') or 0)
-- 检查 freeze + load 是否大于 capacity
if freeze + load >= capacity then
    return 0
end

-- 抢班期资源redis key 是否存在
if redis.call('exists', periodAllowance) == 0 then
    return -1
end
-- 获取 freeze, load, capacity 值
local pFreeze = tonumber(redis.call('hget', periodAllowance, 'freeze') or 0)
local pLoad = tonumber(redis.call('hget', periodAllowance, 'load') or 0)
local pCapacity = tonumber(redis.call('hget', periodAllowance, 'capacity') or 0)
if pFreeze + pLoad >= pCapacity then
    return -1
end

-- 时段下所有老师是否存在
if redis.call('exists', timeAllowance) == 0 then
    return -2
end
local teacherInternalIds = tostring(redis.call('hget', timeAllowance, 'teacherInternalIds') or '')
if string.len(teacherInternalIds) == 0 then
    return -2
end
-- 分割老师
local teacherInternalIdLst = luaSplit(teacherInternalIds, ',')
-- 抢时段成功，分配的老师id
local finalteacherId = '0'
-- 抢时段成功，分配的老师班级容量承载
local finalTeacherClassCapacityKey
-- 抢时段成功，分配的老师时段承载
local finalTeacherTimeCapacityKey
-- 老师班级剩余容量
local classAllowance = 0
-- 获取班级容量足够且最多的老师，老师时段承载要够
for i = 1, #teacherInternalIdLst, 1 do
    -- 加载班期下老师班级容量承载
    local teacherClassCapacityKey = teacherClassCapacity .. ':' .. classPeriodId .. ':' .. teacherInternalIdLst[i]
    local tcFreeze = tonumber(redis.call('hget', teacherClassCapacityKey, 'freeze') or 0)
    local tcLoad = tonumber(redis.call('hget', teacherClassCapacityKey, 'load') or 0)
    local tcCapacity = tonumber(redis.call('hget', teacherClassCapacityKey, 'capacity') or 0)

    -- 加载老师时段承载
    local teacherTimeCapacityKey = teacherTimeCapacity .. ':' .. teacherInternalIdLst[i] .. ':' .. weekDayTime
    local ttFreeze = tonumber(redis.call('hget', teacherTimeCapacityKey, 'freeze') or 0)
    local ttLoad = tonumber(redis.call('hget', teacherTimeCapacityKey, 'load') or 0)
    local ttCapacity = tonumber(redis.call('hget', teacherTimeCapacityKey, 'capacity') or 0)

    local tcAllowance = tcCapacity - (tcFreeze + tcLoad)
    if (tcAllowance > 0 ) and (tcAllowance > classAllowance) and (ttFreeze + ttLoad < ttCapacity) then
        -- 老师班期下班级容量够， 且老师时段承载容量够
        finalteacherId = teacherInternalIdLst[i]
        finalTeacherClassCapacityKey = teacherClassCapacityKey
        finalTeacherTimeCapacityKey = teacherTimeCapacityKey
        classAllowance = tcAllowance
    end
end
if finalteacherId == '0' then
    -- 没有符合条件的老师
    return -3
end

-- 冻结班期下老师班容名额
redis.call('hincrby', finalTeacherClassCapacityKey, 'freeze', 1)
-- 冻结老师时段承载名额
redis.call('hincrby', finalTeacherTimeCapacityKey, 'freeze', 1)

-- 时段及班期都有余量，增加freeze值
redis.call('hincrby', timeAllowance, 'freeze', 1)
redis.call('hincrby', periodAllowance, 'freeze', 1)
-- 设置抢时段成功
redis.call("HSET", grabTimekey, handoverId, 1)

-- 占用老师
-- 返回分配的老师
return tonumber(finalteacherId)
