---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shanjian.
--- DateTime: 2024/8/16 19:12
---

print(type(true))
print(type(false))
print(type(nil))

if false or nil then
    print("至少有一个是true")
else
    print("false和nil都为false")
end
if 0 then
    print("数字 0 为 true")
else
    print("数字 0 为 false")
end