---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shanjian.
--- DateTime: 2024/8/16 17:30
---


tab1 = { key1 = "val1", key2 = "val2", "val3" }
print(debug.debug())
for k, v in pairs(tab1) do
    print(k .. " - " .. v)
end

print("--------")

tab1.key1 = nil
for k,v in pairs(tab1) do
    print(k .. " — " .. v)
end
