---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shanjian.
--- DateTime: 2024/8/16 17:24
---
print("Hello Lua!")

print(type("Hello Lua!"))
print(type(10.4*3))
print(type(print))
print(type(true))
print(type(nil))
print(type(type(X)))
print(type(a))

print("-----------")
print(type(X))
print(type(X)==nil)
print(type(X)=="nil")