---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shanjian.
--- DateTime: 2024/8/16 19:33
---

function factorial1(n)
    if n == 0 then
        return 1
    else
        return n * factorial1(n - 1)
    end
end

print(factorial1(5)) -- 120
factorial2 = factorial1
print(factorial2(5)) -- 120


print("----")

function testFun(tab, fun)
    for k, v in ipairs(tab) do
        print(fun(k, v))
    end
end

tab = { key1 = "val1", key2 = "val2" };
print(testFun(tab, function(key, val)
    return key .. "=" .. val
end
))