---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shanjian.
--- DateTime: 2024/8/20 15:34
---

s, e = string.find("hello world", "world")
print(s, e)

-- 多返回值
function maximum(a)
    local mi = 1
    local m = a[mi]
    for i, val in ipairs(a) do
        if val > m then
            mi = i
            m = val
        end
    end
    return m, mi
end

print(maximum({ 10, 20, 30, 40, 50 }))


-- 可变参数
function add(...)
    local s = 0
    for i, v in ipairs { ... } do
        --> {...} 表示一个由所有变长参数构成的数组
        s = s + v
    end
    return s
end
print(add(3, 4, 5, 6, 7))