---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shanjian.
--- DateTime: 2024/8/16 19:17
---
local tbl = {}

local tbl2 = { "apple", "pear", "orange", "grape" }

a = {}
a["key"] = "value"
key = 10;
a[key] = 22;
a[key] = a[key] + 1;
for k, v in pairs(a) do
    print(k .. ":" .. v)
end