---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shanjian.
--- DateTime: 2024/8/16 19:28
---

local tbl = { "apple", "pear", "orange", "grape" }

for key, val in ipairs(tbl) do
    print("Key", key)
    print("Value", val)
end

print("-------------------")

-- table 不会固定长度大小，有新数据添加时 table 长度会自动增长，没初始的 table 都是 nil。
a3 = {}
for i = 1, 10 do
    a3[i] = i
end

a3["key"] = "val"
print(a3["key"])
print(a3["none"])